spring.application.name=discipline-tracker
spring.datasource.url = jdbc:mysql://localhost:3306/Descipline_tracker
spring.datasource.username=root
spring.datasource.password = ashraf@cc11

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
